spring:
  application:
    name: Cealum博客

  thymeleaf:
    mode: HTML
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 10MB
server:
  servlet:
    context-path: /blog
comment.avatar: /images/boy.png
#打印sql语句
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl