spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.30:3306/qzj_blog?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 321


  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false

logging:
  level:
    root: warn
    com.qzjblog.blog: info
  file:
    name: log/blog-pro.log



