spring:
  application:
    name: Cealum博客

  thymeleaf:
    mode: HTML
  profiles:
    active: pro
  servlet:
    multipart:
      max-file-size: 10MB
server:
  servlet:
    context-path: /blog
user.manAvatar: /images/boy.png
user.womanAvatar: /images/girl.png
blog.defaultPicture: /images/wel.jpg
#打印sql语句
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl